<?php


function wp_compare_tables_options()
{
	tabels_header('options');
?>

<div class="wrap">
<form method="post" action="options.php">
<?php wp_nonce_field('update-options'); ?>

<?php if ( tabels_return_get('updated') == 'true' ) echo '<div id="message" class="updated"><p><strong>Configuration saved.</strong></p></div>'; ?>


    <div class="postbox-container" style="width: 100%">
        <div class="metabox-holder">
            <div class="meta-box-sortables">
                <div class="postbox" id="first">
                    <div class="handlediv" title="Click to toggle"><br /></div>
                    <h3 class="hndle"><span><?php _e('Table Design', 'wp-compare-tables'); ?></span></h3>
                    <div class="inside">
                    
                        <p><?php _e('Choose one of the default table designs. Choose "None", if you do not want any design, and are using your own CSS code.', 'wp-compare-tables'); ?></p>
                        
						<table class="form-table">				
							<tr>
								<th><?php _e('Design Type', 'wp-compare-tables'); ?></th>
								<td>
									<table cellspacing="0" cellpadding="0">
									
										<tr>
											<td>
												<img src="<?php echo WP_PLUGIN_URL . '/wp-compare-tables/templates/stylesheets/images/none.png'; ?>" style="border: 1px solid #e7e7e7;" />
											</td>
											<td>
												<img src="<?php echo WP_PLUGIN_URL . '/wp-compare-tables/templates/stylesheets/images/default.png'; ?>" style="border: 1px solid #e7e7e7;" />
											</td>					
										</tr>	
										<tr>
											<td style="text-align: center;">
												<label><input type="radio" name="wp-compare-tables-designtype" style="padding-right: 10px;" value='none' <?php echo (get_option('wp-compare-tables-designtype') == 'none' ? ' checked="checked"' : ''); ?> /> <?php _e('None', 'wp-compare-tables'); ?></label>
											</td>
											<td style="text-align: center;">
												<label><input type="radio" name="wp-compare-tables-designtype" style="padding-right: 10px;" value='default' <?php echo (get_option('wp-compare-tables-designtype') == 'default' ? ' checked="checked"' : ''); ?> /> <?php _e('Clean: Blue', 'wp-compare-tables'); ?></label>
											</td>
										</tr>
									
									</table>
								</td>
							</tr>		
						</table>
                        
                    </div>
                </div>
                <div class="postbox" id="second">
                    <div class="handlediv" title="Click to toggle"><br /></div>
                    <h3 class="hndle"><span><?php _e('Uninstall', 'wp-compare-tables'); ?></span></h3>
                    <div class="inside">
                        <p><?php _e('Do you want to uninstall this plugin? No problem. Just check the box below before doing so. This will delete any data that previously was generated by WP Compare Tables.', 'wp-compare-tables'); ?></p>

						<table class="form-table"> 
							<tr valign="top"> 
							<th scope="row"><?php _e('Uninstall', 'wp-compare-tables'); ?></th> 
							<td>
								<fieldset>
									<label for="uninstall"> 
										<input name="wp_compare_tables_uninstall" type="checkbox" id="uninstall" value="true"<?php echo (get_option('wp_compare_tables_uninstall') == 'true' ? ' checked="checked"' : ''); ?> /> 
										<?php _e('Check the box and deactivate this plugin before removing the files completely.', 'wp-compare-tables'); ?>
									</label>
									<br /> 
							</fieldset>
							</td> 
							</tr>
						</table>
						
                    </div>
                </div>

            </div>
        </div>
    </div>

<input type="hidden" name="action" value="update" />
<input type="hidden" name="page_options" value="wp_compare_tables_uninstall,wp-compare-tables-designtype" />

<p class="submit">
<input type="submit" class="button-primary" value="<?php _e('Save Changes', 'wp-compare-tables'); ?>" />
</p>

</form>
</div>

<?php	
	tabels_footer();
}